In [2]:
from sentence_transformers import SentenceTransformer
from FlagEmbedding import FlagModel
import torch
import pandas as pd
import numpy as np

In [3]:
model = SentenceTransformer("bge-large-zh",device='cuda')
model.eval()

SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': True}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': True, 'pooling_mode_mean_tokens': False, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [6]:
import pandas as pd
import numpy as np

In [3]:
patent_co=pd.read_csv('E:\Documents\Jupyter/data/融资公司专利2024.csv',usecols=['序号', '标题 (中文)', '摘要 (中文)', 'Co','申请号','申请人','申请日','专利类型','公开（公告）号','table'])

In [8]:
patent_co.columns

Index(['Co', '序号', '标题 (中文)', '摘要 (中文)', '申请人', '申请日', '申请号', '公开（公告）号',
       '专利类型'],
      dtype='object')

In [30]:
patent_doc=patent_co['标题 (中文)'].str.cat(patent_co['摘要 (中文)'].replace(np.nan,''),sep=':')
patent_doc

0          竖式烧结矿冷却机:本发明为一种具有环形风道和全密闭结构的竖式烧结矿冷却机，属冷却机技术领域；...
1          具有抗静电性的轻垢液体洗衣洗涤剂:本发明提供一种透明或半透明的具有抗静电性 的轻垢液体洗衣洗...
2          麦白霉素胃溶片的生产工艺技术:一种麦白霉素胃溶片的生产工艺技术，以国产原 料组成新的配方，替...
3                                              药品包装盒:省略其它视图。
4          变幅摇头电风扇:一种变幅摇头电风扇，包括有扇座、扇体，其特征 在于扇体变幅摇头机构由电机驱动...
                                 ...                        
1897512    机器人标定方法、系统及机器人:本发明涉及机器人标定技术领域，具体而言，涉及一种机器人标定方法...
1897513    一种多普勒激光测风雷达径向风速标定方法:本发明旨在提供一种满足高精度要求、目标校准不确定度低...
1897514    一种晶圆激光开槽装置及开槽方法:本发明旨在提供一种能实现双通道光路调节，能同时进行定位开槽和...
1897515    一种微型塑料件激光焊接系统以及焊接方法:本发明提供一种微型塑料件激光焊接系统以及焊接方法，本...
1897516    可拆卸式电池模块:本实用新型公开了可拆卸式电池模块，涉及电池模块技术领域，包括壳体，所述壳体...
Name: 标题 (中文), Length: 1897517, dtype: object

In [8]:
patent_co['摘要长度']=patent_co['摘要 (中文)'].replace(np.nan,'').str.len()

In [31]:
patent_doc.str.len().describe()

count    1.897517e+06
mean     2.560255e+02
std      7.372450e+01
min      3.000000e+00
25%      2.180000e+02
50%      2.750000e+02
75%      3.050000e+02
max      1.283900e+04
Name: 标题 (中文), dtype: float64

In [22]:
patent_co.loc[patent_co['摘要长度']<10,'摘要 (中文)'].dropna().to_list()

['省略其它视图。',
 '打开门的主视图',
 '省略其它视图。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '省略仰视图。',
 '省略仰视图。',
 '省略后视图。',
 '省略仰视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '省略其它视图。',
 '请求保护色彩。',
 '省略其它视图。',
 '省略后视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '省略其它视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '请求保护色彩。',
 '省略其它视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '省略其它视图。',
 '省略后视图。',
 '请求保护色彩。',
 '请求保护色彩。',
 '省略仰视图。',
 '省略其它视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '请求保护色彩。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略后视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略其它视图。',
 '省略仰视图。',
 '省略其它视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略仰视图。',
 '省略其它视图。',
 '省略仰视图。',
 '省略其它视图。',
 '请求保护色彩。',
 '省略其它视图。',


In [24]:
patent_co.loc[patent_co['摘要长度']<10,'摘要长度']=0

In [9]:
patent_doc.index

NameError: name 'patent_doc' is not defined

In [18]:
patent_doc[patent_doc.str.len()>12000]

892140    电脑的图形用户界面:1.本外观设计产品的名称：电脑的图形用户界面。2.本外观设计产品的用途：...
Name: 标题 (中文), dtype: object

In [20]:
model.encode(patent_doc.iloc[892140])

array([-0.00272806, -0.02407967, -0.02734151, ...,  0.02709071,
        0.01606625, -0.02833204], dtype=float32)

In [24]:
sentences_embeddings  = model.encode(patent_doc[:5], normalize_embeddings=True)
sentences_embeddings.shape

(5, 1024)

In [33]:
patent_co[patent_doc.isna()]

Empty DataFrame
Columns: [Co, 序号, 标题 (中文), 摘要 (中文), 申请人, 申请日, 申请号, 公开（公告）号, 专利类型]
Index: []

In [34]:
torch.cuda.is_available()

True

In [35]:
%%time
embeddings=model.encode(patent_doc,convert_to_tensor=True,  normalize_embeddings=True, device='cuda')

CPU times: total: 7h 44min 30s
Wall time: 7h 7min 13s


In [37]:
sentences_embeddings=embeddings.cpu().numpy()
sentences_embeddings.shape

(1897517, 1024)

In [38]:
np.save('E:\Documents\Jupyter\data\融资公司专利2024_embeddings.npy',sentences_embeddings)

In [25]:
import pickle

In [58]:
payload=patent_co[['Co','序号','申请号','公开（公告）号','标题 (中文)']].to_dict(orient="records")

In [26]:
payload_1=patent_co[['摘要长度','table']].to_dict(orient="records")

In [63]:
len(payload),payload[0]

(1897517,
 {'Co': '重庆钢铁股份有限公司',
  '序号': 123,
  '申请号': 'CN93117175.X',
  '公开（公告）号': 'CN1050661C',
  '标题 (中文)': '竖式烧结矿冷却机'})

In [28]:
len(payload_1),payload_1[0]

(1897517, {'摘要长度': 160, 'table': 'patent202210'})

In [61]:
with open('E:\Documents\Jupyter\data\融资公司专利2024_payloads.pkl', 'wb') as file:
    pickle.dump(payload, file)

In [30]:
with open('E:\Documents\Jupyter\data\融资公司专利2024_payloads_1.pkl', 'wb') as file:
    pickle.dump(payload_1, file)

In [54]:
queries='问答交互方法和装置'
queries_embeddings  = model.encode(queries, normalize_embeddings=True)
similarity = queries_embeddings @ sentences_embeddings.T
res=pd.Series(similarity.flatten(),index=patent_co['标题 (中文)'],name=queries)
res.sort_values(ascending=False).head(10)

标题 (中文)
问答交互方法和装置、计算机设备及计算机可读存储介质        0.902388
问答交互方法和装置、计算机设备及计算机可读存储介质        0.902388
人机交互方法及装置、存储介质、终端                0.898434
一种应答方法和装置                        0.889229
一种应答方法和装置                        0.889229
一种会话交互方法                         0.880753
一种FAQ问答库泛化方法、装置及设备               0.866741
情感交互方法及装置、计算机可读存储介质、计算机设备        0.863018
情感交互方法及装置、计算机可读存储介质、计算机设备        0.863018
知识库构建、基于知识库的智能问答方法及装置、存储介质、终端    0.859648
Name: 问答交互方法和装置, dtype: float32

In [47]:
similarity.reshape(-1)

array([0.6941302 , 0.6752223 , 0.6931166 , ..., 0.71921104, 0.69920707,
       0.7082873 ], dtype=float32)

In [55]:
largest_idx = np.argsort(similarity.reshape(-1))[-5:][::-1]#flatten [:-6:-1]
patent_co['标题 (中文)'].iloc[largest_idx],similarity.reshape(-1)[largest_idx]

(805646    问答交互方法和装置、计算机设备及计算机可读存储介质
 805647    问答交互方法和装置、计算机设备及计算机可读存储介质
 805634            人机交互方法及装置、存储介质、终端
 954563                    一种应答方法和装置
 954557                    一种应答方法和装置
 Name: 标题 (中文), dtype: object,
 array([0.9023882 , 0.9023882 , 0.8984344 , 0.88922876, 0.88922876],
       dtype=float32))

In [53]:
patent_co.iloc[similarity.argmax()]

Co                  上海智臻智能网络科技股份有限公司
序号                           1301366
标题 (中文)    问答交互方法和装置、计算机设备及计算机可读存储介质
摘要 (中文)                          NaN
申请人                 上海智臻智能网络科技股份有限公司
申请日                       2018-11-21
申请号                     HK18114906.4
公开（公告）号                   HK1255831B
专利类型                            发明授权
Name: 805646, dtype: object

In [65]:
df_co=pd.read_excel('E:\Documents\Jupyter\data\公司融资变量2_20240301.xlsx',usecols=['公司序号','公司简称','工商全称','公司简介','行业'])
df_co.shape

(47920, 5)

In [66]:
df_co_1=pd.read_excel('E:\Documents\Jupyter\data\df_patent_invest_diff.xlsx',usecols=['序号','公司名','公司全称','简介'])
df_co_1.shape

(3206, 4)

In [67]:
df_co_1['公司序号']=df_co['公司序号'].max()+df_co_1['序号']
df_co_1['行业']='金融科技'

In [70]:
df_co_1[df_co.columns]=df_co_1[['公司序号','公司名','公司全称','简介','行业']]
df_co_11=df_co_1[df_co.columns].drop_duplicates()
df_co_11.shape

(258, 5)

In [73]:
df_co_all=pd.concat([df_co.drop_duplicates('公司序号'),df_co_11],axis=0)
df_co_all.shape

(25413, 5)

In [77]:
df_co_all.reset_index(drop=True).to_excel('E:\Documents\Jupyter\data\行业公司名简介_2024.xlsx')

In [31]:
df_co_all=pd.read_excel('E:\Documents\Jupyter\data\行业公司名简介_2024.xlsx',index_col=0)

In [79]:
df_co_all.reset_index(drop=True,inplace=True)

In [34]:
df_co_all.count()

公司序号    25413
公司简称    25413
工商全称    25285
公司简介    25400
行业      25413
dtype: int64

In [43]:
df_co_all['简介长度']=df_co_all['公司简介'].str.len()
df_co_all['简介长度'].describe()

count    25400.000000
mean       104.535709
std         48.140552
min          3.000000
25%         76.000000
50%         95.000000
75%        124.000000
max       1040.000000
Name: 简介长度, dtype: float64

In [37]:
(df_co_all['简介长度']<10).sum()

83

In [41]:
df_co_all.loc[df_co_all['简介长度']<=5,'公司简介']

18812    爱瘦APP
19753      已倒闭
25201     民营银行
25252     民营银行
25315     民营银行
25335     财险公司
25361    综合性企业
Name: 公司简介, dtype: object

In [92]:
df_co_all['公司简称']=df_co_all['公司简称'].astype(str)

In [89]:
df_co_all['工商全称']=df_co_all['工商全称'].replace(np.nan,'').astype(str)
df_co_all['公司简介']=df_co_all['公司简介'].replace(np.nan,'').astype(str)

In [90]:
df_co_all.count()

公司序号    25413
公司简称    25413
工商全称    25413
公司简介    25413
行业      25413
dtype: int64

In [94]:
co_doc=df_co_all['公司简称'].str.cat(df_co_all['工商全称'],sep=' ').str.cat(df_co_all['公司简介'],sep=':')
co_doc

0        SciXair空气净化器 天津蔚蓝科技有限公司:SciXair是一家空气净化器开发设计和销售...
1        iKair家庭环境管家 北京超感时空科技有限公司:iKair家庭环境管家是一个专注于家庭室内...
2        云印技术 云印技术（深圳）有限公司:云印技术专注包装产业的数字化商业价值探索，通过云计算、大...
3        第一人居 第一摩码人居环境科技（北京）有限公司:第一人居是一家智能空气净化产品研发商，公司致...
4        R2专业物品管理 上海合阖信息科技有限公司:R2专业物品管理是一家致力于信息化、数字化提供更...
                               ...                        
25408                          连连数字 连连数字科技股份有限公司:跨境支付金融服务商
25409                              快钱 快钱支付清算信息有限公司:互联网金融平台
25410                      九次方大数据 九次方大数据信息集团有限公司:金融大数据服务平台
25411                      平安医保科技 平安医疗健康管理股份有限公司:医保/商保管理平台
25412                     爱因互动 爱因互动科技发展（北京）有限公司:智能对话机器人提供商
Name: 公司简称, Length: 25413, dtype: object

In [95]:
%%time
co_embeddings=model.encode(co_doc,convert_to_tensor=True,  normalize_embeddings=True, device='cuda')

CPU times: total: 2min 49s
Wall time: 2min 33s


In [98]:
%%time
sentences_embeddings=co_embeddings.cpu().numpy()
np.save('E:\Documents\Jupyter\data\行业公司名简介2024_embeddings.npy',sentences_embeddings)
payload=df_co_all[['公司序号','公司简称','工商全称','行业']].to_dict(orient="records")
with open('E:\Documents\Jupyter\data\行业公司名简介2024_payloads.pkl', 'wb') as file:
    pickle.dump(payload, file)

CPU times: total: 234 ms
Wall time: 401 ms


In [99]:
payload[1024]

{'公司序号': 1024, '公司简称': '海印环保', '工商全称': '上海海印环保科技股份有限公司', '行业': '传统制造'}

In [103]:
queries='上海海印环保科技股份有限公司'
queries_embeddings  = model.encode(queries, normalize_embeddings=True)
similarity = queries_embeddings @ sentences_embeddings.T
largest_idx = np.argsort(similarity.reshape(-1))[-5:][::-1]#flatten [:-6:-1]
df_co_all['工商全称'].iloc[largest_idx],similarity.reshape(-1)[largest_idx]

(1620       上海环境节能工程股份有限公司
 3839         上海环境集团股份有限公司
 25156       深圳市金证科技股份有限公司
 25366    星环信息科技（上海）股份有限公司
 1819       上海复洁环保科技股份有限公司
 Name: 工商全称, dtype: object,
 array([0.83436865, 0.8272115 , 0.82697636, 0.8203628 , 0.82031786],
       dtype=float32))

In [105]:
queries_1='海印环保 上海海印环保科技股份有限公司'
queries_1_embeddings  = model.encode(queries_1, normalize_embeddings=True)
similarity = queries_embeddings @ queries_1_embeddings.T
similarity

0.9901897

In [106]:
co_name_embeddings=model.encode(df_co_all['公司简称'].str.cat(df_co_all['工商全称'],sep=' '),convert_to_tensor=True,  normalize_embeddings=True, device='cuda')
co_sentences_embeddings=co_name_embeddings.cpu().numpy()

In [111]:
sentences_embeddings=np.vstack((co_sentences_embeddings,sentences_embeddings))
payload+=df_co_all[['公司序号','公司简称','工商全称','行业']].to_dict(orient="records")

In [113]:
sentences_embeddings.shape,len(payload)

((50826, 1024), 50826)

In [119]:
queries='海泰环保科技'
queries_embeddings  = model.encode(queries, normalize_embeddings=True)
similarity = queries_embeddings @ sentences_embeddings.T
largest_idx = np.argsort(similarity.reshape(-1))[-5:][::-1]#flatten [:-6:-1]
np.array(payload)[largest_idx],similarity.reshape(-1)[largest_idx]

(array([{'公司序号': 202, '公司简称': '海泰环保', '工商全称': '天津海泰环保科技发展股份有限公司', '行业': '传统制造'},
        {'公司序号': 4568, '公司简称': '海云环保', '工商全称': '浙江海云环保有限公司', '行业': '传统制造'},
        {'公司序号': 4545, '公司简称': '国泰环保', '工商全称': '杭州国泰环保科技股份有限公司', '行业': '传统制造'},
        {'公司序号': 3300, '公司简称': '海岳环境', '工商全称': '山东海岳环境科技股份有限公司', '行业': '传统制造'},
        {'公司序号': 1024, '公司简称': '海印环保', '工商全称': '上海海印环保科技股份有限公司', '行业': '传统制造'}],
       dtype=object),
 array([0.9557438 , 0.9164884 , 0.91337204, 0.9105132 , 0.9074804 ],
       dtype=float32))

In [117]:
np.save('E:\Documents\Jupyter\data\行业公司名简介2024_embeddings.npy',sentences_embeddings)
payload=df_co_all[['公司序号','公司简称','工商全称','行业']].to_dict(orient="records")
with open('E:\Documents\Jupyter\data\行业公司名简介2024_payloads.pkl', 'wb') as file:
    pickle.dump(payload, file)

In [123]:
len(payload)

25413

In [128]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance,Batch, VectorParams,PointStruct,OptimizersConfigDiff,HnswConfigDiff,CollectionStatus,Filter, FieldCondition, MatchValue,Range,SearchParams,PointIdsList
client = QdrantClient(host="10.10.10.5", grpc_port=6334, prefer_grpc=True)

In [125]:
tmp1=df_co_all[['公司序号','公司简称','工商全称','行业']]
tmp1['profile']=0

In [126]:
payload=df_co_all[['公司序号','公司简称','工商全称','行业']].to_dict(orient="records")+df_co_all[['公司序号','公司简称','工商全称','行业','profile']].to_dict(orient="records")

In [44]:
payload=df_co_all[['公司序号','公司简称','工商全称','行业','简介长度']].to_dict(orient="records")+df_co_all[['公司序号','公司简称','工商全称','行业']].to_dict(orient="records")

In [47]:
with open('E:\Documents\Jupyter\data\行业公司名简介2024_payloads.pkl', 'wb') as file:
    pickle.dump(payload, file)

In [46]:
len(payload)

50826

In [130]:
points=Batch(
    ids= list(range(len(payload))),
    vectors=sentences_embeddings.tolist(),
    payloads=payload,
)

In [133]:
Distance

<enum 'Distance'>

In [135]:
sentences_embeddings.shape[1]

1024

In [136]:
client.create_collection(
    collection_name='行业公司名简介_2.5w',
    vectors_config=VectorParams(size=sentences_embeddings.shape[1], distance=Distance.DOT),)

True

In [137]:
client.upsert(collection_name='行业公司名简介_2.5w',points = points)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [ ]:
def get_embedding(text):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze()

In [ ]:
from torch.utils.data import DataLoader, Dataset
class MyDataset(Dataset):
    def __init__(self, texts):
        self.texts = texts
    
    def __len__(self):
        return len(self.texts)
    
    def __getitem__(self, idx):
        return self.texts[idx]

device = 'cuda' if torch.cuda.is_available() else 'cpu'
batch_size = 64  # 根据GPU的内存情况调整批处理大小
dataset = MyDataset(patent_doc)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

all_embeddings = []
for batch in dataloader:
    # 将批次数据加载到GPU
    embeddings = model.encode(batch, convert_to_tensor=True, normalize_embeddings=True, device=device)
    # 将结果移动到CPU并转换为numpy数组，然后存储
    all_embeddings.append(embeddings.cpu().numpy())

all_embeddings = np.vstack(all_embeddings)
all_embeddings.shape